/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uk.chromis.pos.payment;


import java.awt.Component;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import uk.chromis.format.Formats;
import uk.chromis.pos.customers.CustomerInfoExt;
import uk.chromis.pos.forms.AppLocal;
import uk.chromis.pos.util.RoundUtils;

/**
 *
 * @author User
 */
public class JPaymentCredit extends javax.swing.JPanel implements JPaymentInterface {
    
  
    private final JPaymentNotifier notifier;
    private CustomerInfoExt customerext;
    private double m_dPaid;
    private double m_dTotal;
    
    /** Creates new form JPaymentDebt
     * @param notifier */
    public JPaymentCredit(JPaymentNotifier notifier) {

        this.notifier = notifier;

        initComponents();

        m_jTendered.addPropertyChangeListener("Edition", new RecalculateState());
        m_jTendered.addEditorKeys(m_jKeys);
        
    }

    private void printState()
    {
        
    }
    @Override
    public void activate(CustomerInfoExt customerext, double dTotal, String transactionID) {
        this.customerext = customerext;
        m_dTotal = dTotal;
        m_jTendered.reset();
        
        if (customerext == null) {
            m_jName.setText(null);
            m_jNotes.setText(null);
            txtCost.setText(null);
            txtFincred.setText(null);
            txtCurcred.setText(null);

            m_jKeys.setEnabled(false);
            m_jTendered.setEnabled(false);

        }else {
            m_jName.setText(customerext.getName());
            m_jNotes.setText(customerext.getNotes());
            txtCost.setText(Formats.CURRENCY.formatValue(RoundUtils.getValue(m_dPaid)));
            m_jCredit_Purchase.setText(Formats.CURRENCY.formatValue(new Double(m_dPaid)));
       //     System.out.println(customerext.getCurdebt();
            txtCurcred.setText(Formats.CURRENCY.formatValue(RoundUtils.getValue(customerext.getCredit())));

            if (RoundUtils.compare(RoundUtils.getValue(customerext.getCurdebt()), RoundUtils.getValue(customerext.getMaxdebt())) >= 0) {
                m_jKeys.setEnabled(false);
                m_jTendered.setEnabled(false);
            } else {
                m_jKeys.setEnabled(true);
                m_jTendered.setEnabled(true);
                m_jTendered.activate();
            }
        }

        printState();
    }

    @Override
    public PaymentInfo executePayment() {
        return new PaymentInfoTicket(m_dPaid, "credit");
    }

    @Override
    public Component getComponent() {
    return this;
    }
    
    private class RecalculateState implements PropertyChangeListener {

        @Override
        public void propertyChange(PropertyChangeEvent evt) {
            printState();
        }
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        m_jCredit_Purchase = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        m_jName = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel220 = new javax.swing.JLabel();
        txtCurcred = new javax.swing.JTextField();
        jLabel420 = new javax.swing.JLabel();
        txtFincred = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        m_jNotes = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        txtCost = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jlblMessage = new javax.swing.JTextArea();
        m_jKeys = new uk.chromis.editor.JEditorKeys();
        m_jTendered = new uk.chromis.editor.JEditorCurrencyPositive();

        setMinimumSize(new java.awt.Dimension(202, 275));
        setPreferredSize(new java.awt.Dimension(593, 397));
        setLayout(new java.awt.BorderLayout());

        jPanel4.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel8.setText(AppLocal.getIntString("label.cred")); // NOI18N
        jPanel4.add(jLabel8);
        jLabel8.setBounds(20, 20, 100, 25);

        m_jCredit_Purchase.setBackground(new java.awt.Color(204, 255, 51));
        m_jCredit_Purchase.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        m_jCredit_Purchase.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        m_jCredit_Purchase.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(javax.swing.UIManager.getDefaults().getColor("Button.darkShadow")), javax.swing.BorderFactory.createEmptyBorder(1, 4, 1, 4)));
        m_jCredit_Purchase.setOpaque(true);
        m_jCredit_Purchase.setPreferredSize(new java.awt.Dimension(200, 30));
        jPanel4.add(m_jCredit_Purchase);
        m_jCredit_Purchase.setBounds(120, 20, 200, 30);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setText(AppLocal.getIntString("label.name")); // NOI18N
        jPanel4.add(jLabel3);
        jLabel3.setBounds(20, 60, 100, 25);

        m_jName.setEditable(false);
        m_jName.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jPanel4.add(m_jName);
        m_jName.setBounds(120, 60, 200, 25);

        jLabel12.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel12.setText(AppLocal.getIntString("label.notes")); // NOI18N
        jPanel4.add(jLabel12);
        jLabel12.setBounds(20, 90, 100, 25);

        jLabel220.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel220.setText(AppLocal.getIntString("label.curcred")); // NOI18N
        jPanel4.add(jLabel220);
        jLabel220.setBounds(20, 140, 100, 25);

        txtCurcred.setEditable(false);
        txtCurcred.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtCurcred.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel4.add(txtCurcred);
        txtCurcred.setBounds(120, 140, 130, 25);

        jLabel420.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel420.setText(AppLocal.getIntString("label.fincred")); // NOI18N
        jPanel4.add(jLabel420);
        jLabel420.setBounds(20, 200, 100, 25);

        txtFincred.setEditable(false);
        txtFincred.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtFincred.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel4.add(txtFincred);
        txtFincred.setBounds(120, 200, 130, 25);

        m_jNotes.setEditable(false);
        m_jNotes.setBackground(new java.awt.Color(240, 240, 240));
        m_jNotes.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        m_jNotes.setEnabled(false);
        jScrollPane1.setViewportView(m_jNotes);

        jPanel4.add(jScrollPane1);
        jScrollPane1.setBounds(120, 90, 200, 40);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setText(AppLocal.getIntString("label.discount")); // NOI18N
        jPanel4.add(jLabel5);
        jLabel5.setBounds(20, 170, 100, 25);

        txtCost.setEditable(false);
        txtCost.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtCost.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel4.add(txtCost);
        txtCost.setBounds(120, 170, 130, 25);

        jlblMessage.setEditable(false);
        jlblMessage.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jlblMessage.setForeground(new java.awt.Color(255, 0, 51));
        jlblMessage.setLineWrap(true);
        jlblMessage.setWrapStyleWord(true);
        jlblMessage.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jlblMessage.setFocusable(false);
        jlblMessage.setPreferredSize(new java.awt.Dimension(300, 72));
        jlblMessage.setRequestFocusEnabled(false);
        jPanel6.add(jlblMessage);

        jPanel4.add(jPanel6);
        jPanel6.setBounds(-20, 290, 390, 70);

        m_jKeys.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_jKeysActionPerformed(evt);
            }
        });
        jPanel4.add(m_jKeys);
        m_jKeys.setBounds(390, 10, 190, 250);

        m_jTendered.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel4.add(m_jTendered);
        m_jTendered.setBounds(400, 270, 132, 25);

        add(jPanel4, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void m_jKeysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_jKeysActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m_jKeysActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel220;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel420;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jlblMessage;
    private javax.swing.JLabel m_jCredit_Purchase;
    private uk.chromis.editor.JEditorKeys m_jKeys;
    private javax.swing.JTextField m_jName;
    private javax.swing.JTextArea m_jNotes;
    private uk.chromis.editor.JEditorCurrencyPositive m_jTendered;
    private javax.swing.JTextField txtCost;
    private javax.swing.JTextField txtCurcred;
    private javax.swing.JTextField txtFincred;
    // End of variables declaration//GEN-END:variables
}
